import type { Metadata } from "next";
import MainFooter from "@/widgets/MainFooter";
import MainHeader from "@/widgets/MainHeader";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootWebLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<MainHeader />
			<main className="main-layout flex-1">{children}</main>
			<MainFooter />
		</>
	);
}
